// services/license.js — safe global registration
const LS='BILLIARD_LICENSE_TOKEN_V1', TR='BILLIARD_TRIAL_V1', D=14;
export const PRICING={ lite:{monthly:600,tablesLimit:5}, pro:{monthly:900,tablesLimit:10}, buy5:{upfront:20000,monthly:250,tablesLimit:5}, buy10:{upfront:30000,monthly:250,tablesLimit:10} };
function now(){return Math.floor(Date.now()/1000)}; function days(x){return Math.max(0,Math.ceil((x-now())/86400))}
function tok(){try{return JSON.parse(localStorage.getItem(LS))}catch{return null}}
function save(o){localStorage.setItem(LS, JSON.stringify(o||null))}
export async function getStatus(){ const t=tok(); if(t&&t.mode){ if(t.mode==='perpetual') return {ok:true,mode:'perpetual',plan:t.plan,tablesLimit:t.tablesLimit,deviceId:'dev'}; if(t.mode==='sub'){const l=days(t.expiresAt||0); if(l>0) return {ok:true,mode:'sub',plan:t.plan,tablesLimit:t.tablesLimit,daysLeft:l,deviceId:'dev'} } } let tr=null; try{tr=JSON.parse(localStorage.getItem(TR)||'null')}catch{} if(!tr){tr={startedAt:now(),until:now()+D*86400}; localStorage.setItem(TR, JSON.stringify(tr))} const left=days(tr.until); if(left>0) return {ok:true,mode:'trial',trialDaysLeft:left,tablesLimit:PRICING.pro.tablesLimit,deviceId:'dev'}; return {ok:false,mode:'expired',deviceId:'dev'} }
export async function activate(key){ key=String(key||'').toUpperCase(); if(!key) throw new Error('Введіть ключ.'); if(key.startsWith('SUB-LITE-')){ save({mode:'sub',plan:'lite',tablesLimit:PRICING.lite.tablesLimit,expiresAt:now()+33*86400}); return {ok:true} } if(key.startsWith('SUB-PRO-')){ save({mode:'sub',plan:'pro',tablesLimit:PRICING.pro.tablesLimit,expiresAt:now()+33*86400}); return {ok:true} } if(key.startsWith('PERP-5-')){ save({mode:'perpetual',plan:'buy5',tablesLimit:PRICING.buy5.tablesLimit}); return {ok:true} } if(key.startsWith('PERP-10-')){ save({mode:'perpetual',plan:'buy10',tablesLimit:PRICING.buy10.tablesLimit}); return {ok:true} } throw new Error('Невідомий формат ключа.') }
export async function deactivate(){ localStorage.removeItem(LS); return {ok:true} }
export async function startTrial(){ const tr={startedAt:now(),until:now()+D*86400}; localStorage.setItem(TR, JSON.stringify(tr)); return {ok:true} }
const api={getStatus,activate,deactivate,startTrial,PRICING}; const g=typeof globalThis!=='undefined'?globalThis:window; try{ if(g && !g.__billiard_license){ Object.defineProperty(g,'__billiard_license',{value:api,writable:false,enumerable:false,configurable:false}) } }catch{} export default api;
